(function(){
const panel=document.createElement('section');panel.id='readiness';panel.innerHTML=`<details><summary><b>운영 준비 · 검토 이력 백업/복원 · 자체 점검</b></summary>
<p>기본 시연: 설비별 LOT 순차 생산, 원료 LOT 1개당 생산 LOT 6개 연결, 공장 전체 07–19시 / 19–다음 날 07시 교대. 원료 LOT는 드럼 용량을 의미하지 않습니다. 240 Batch 버튼으로 적용된 예시를 불러오세요.</p><p>단위: pH(무차원), 고형분 wt%, 점도 mPa·s, D50/D90 nm, LPC 개/mL, 제타 전위 mV, Fe µg/kg, 온도 °C, 차압 kPa, 회전수 rpm, 시간 min.</p><p>빈 QC 값·None은 결측으로 처리하고 계산에서 제외합니다. 미측정인지 미기록인지는 자동 추정하지 않습니다. 필수 ID·시각·공정값 누락은 해당 위치를 경고합니다. 정상 데이터의 평균·표준편차는 출하 규격을 대신하지 않습니다.</p>
<table><tr><th>지금 준비할 정보</th><th>담당자에게 나중에 확인할 정보</th></tr><tr><td>6개 역할별 열 이름과 단위, 날짜 표기·시간대, 익명 처리한 소량 예시, Batch/설비 연결 방법</td><td>제품·처방·시험법별 LSL/USL, 적용 시작일과 개정, 최종 시험 선택 규칙, 정상 비교군 선정 조건</td></tr><tr><td>체크시트는 공장 전체 교대당 1회: 주/야 시작 시각과 적용 구간</td><td>공정 목표·상한, 실제 OCAP 승인 절차, 검토 담당자</td></tr></table>
<p>규격 미확정: 능력 충족 여부·출하 적합성은 보류합니다. 공급사 일반 자료의 수치를 현장 규격으로 자동 적용하지 마세요.</p>
<button id='historyBackup'>검토 이력 백업</button> <button id='historyRestore'>검토 이력 복원</button><input id='historyFile' type='file' accept='.json' hidden> <button id='historyList'>저장 이력 보기</button> <button id='selfCheck'>계산 자체 점검</button>
<p>백업 범위: 저장한 검토 기록과 그 안의 분석 근거. 현재 미저장 입력·전체 CSV·보고서 파일은 포함하지 않습니다. 원본 CSV는 별도 보관하세요. 복원은 기존 기록에 병합하며 동일 ID의 다른 내용은 거부합니다. 백업에는 원본 식별정보가 포함될 수 있습니다.</p><p id='readinessStatus' role='status'></p><div id='historyView'></div></details>`;
document.querySelector('.grid>div').append(panel);
const status=s=>document.querySelector('#readinessStatus').textContent=s;
const digest=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
function validate(rows){if(!Array.isArray(rows)||rows.length>10000)throw Error('이력 배열 또는 기록 수가 잘못되었습니다.');const ids=new Set();for(const e of rows){if(e?.format!=='CMP-REVIEW-1'||typeof e.id!=='string'||!e.id||ids.has(e.id)||typeof e.bid!=='string'||!Number.isFinite(Date.parse(e.saved))||!e.user||!e.report||!Array.isArray(e.standards))throw Error('검토 기록 형식 또는 중복 ID 오류');ids.add(e.id);}}
async function restore(p){if(p?.format!=='CMP-REVIEW-BACKUP-1'||typeof p.payload!=='string'||await digest(p.payload)!==p.sha256)throw Error('백업 형식 또는 손상 검사 실패');const rows=JSON.parse(p.payload);validate(rows);return CMPReview.mergeCases(rows);}
document.querySelector('#historyBackup').onclick=async()=>{try{const payload=JSON.stringify(CMPReview.getCases()),p={format:'CMP-REVIEW-BACKUP-1',created:new Date().toISOString(),payload,sha256:await digest(payload)},a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(p)],{type:'application/json'}));a.href=url;a.download='CMP_Review_Backup_'+new Date().toISOString().replaceAll(':','-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);status('백업 다운로드를 요청했습니다. 체크섬은 손상 확인용이며 작성자 인증은 아닙니다.');}catch(e){status(e.message);}};
document.querySelector('#historyRestore').onclick=()=>document.querySelector('#historyFile').click();
document.querySelector('#historyFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>50*1024*1024)throw Error('50 MB 이하 백업만 복원할 수 있습니다.');status('복원 완료 · 총 '+await restore(JSON.parse(await f.text()))+'건. 현재 분석 결과는 다시 조회하세요.');}catch(err){status('복원 실패: '+err.message);}finally{e.target.value='';}};
document.querySelector('#historyList').onclick=()=>{const rows=CMPReview.getCases();document.querySelector('#historyView').innerHTML=grid(['저장 시각','Batch','담당자','상태','결과'],rows.map(e=>[e.saved,e.bid,e.user.owner,e.user.state,e.user.result]));status(rows.length+'건 · 과거 기록은 변경하지 않고 후속 검토를 새 기록으로 저장합니다. 브라우저 기록은 감사용 변경 방지 저장소가 아닙니다.');};
document.querySelector('#selfCheck').onclick=()=>{try{const s=CMPStats.sd([1,2,3,4,5]),m=CMPStats.mean([1,2,3,4,5]);if(Math.abs(s-Math.sqrt(2.5))>1e-12||m!==3)throw Error('기준값 불일치');status('자체 점검 통과: 평균 3, 표본 표준편차 √2.5. 전체 회귀 검증 결과와 우선 검증 계획은 동봉 안내서를 확인하세요.');}catch(e){status('자체 점검 실패: '+e.message);}};
window.CMPReadiness={restore,validate,digest};
})();
