/* Shared reporting for summary and detail imports. */
const originalSchema=LEGACY_SCHEMA.fields;
let legacyTables={},lastResult=null;
const number=v=>v===''||v==null?null:Number(v);
const display=v=>v==null?'—':typeof v==='number'?v.toLocaleString('ko-KR',{maximumFractionDigits:3}):esc(v);
function grid(headers,rows){return '<div class="scroll"><table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(v=>'<td>'+display(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function statistics(points,value){const n=points.length,mean=n?points.reduce((s,p)=>s+p.value,0)/n:null,sd=n>1?Math.sqrt(points.reduce((s,p)=>s+(p.value-mean)**2,0)/(n-1)):null;return{n,mean,sd,delta:value!=null&&mean!=null?value-mean:null,z:value!=null&&sd>0?(value-mean)/sd:null};}
function trend(m){const pts=m.points.concat(m.value==null?[]:[{id:lastResult.bid,value:m.value,current:true}]);if(!pts.length)return '<p>측정값 없음</p>';const values=pts.map(p=>p.value).concat(m.mean==null?[]:[m.mean]),lo=Math.min(...values),hi=Math.max(...values),pad=(hi-lo)*.15||1,y=v=>130-(v-lo+pad)/(hi-lo+2*pad)*110,x=i=>35+i*510/Math.max(1,pts.length-1);return '<svg viewBox="0 0 580 160" role="img" aria-label="'+esc(m.label)+' 과거 기준군과 선택 Batch 경향"><text x="0" y="15" font-size="11">'+display(hi)+'</text><text x="0" y="145" font-size="11">'+display(lo)+'</text>'+(m.mean==null?'':'<path d="M35 '+y(m.mean)+' H550" stroke="#8196a4" stroke-dasharray="5 4"/>')+'<polyline fill="none" stroke="#0a8079" stroke-width="2" points="'+pts.map((p,i)=>x(i)+','+y(p.value)).join(' ')+'"/>'+pts.map((p,i)=>'<circle cx="'+x(i)+'" cy="'+y(p.value)+'" r="'+(p.current?5:3)+'" fill="'+(p.current?'#c43d40':'#0a8079')+'"><title>'+esc(p.id)+': '+display(p.value)+'</title></circle>').join('')+'<text x="35" y="158" font-size="10">'+esc(pts[0].id)+'</text><text x="440" y="158" font-size="10">'+esc(pts.at(-1).id)+'</text></svg>';}
function analyze(bid){
 if(V2.kinds.every(k=>legacyTables[k])){
  const a=CMP.investigate(legacyTables,bid),p=a.record.Process,b=a.batch;
  const metrics=a.metrics.map(m=>({...m,target:null,points:a.refs.map(id=>({id,value:number(legacyTables.QC.byBatch[id][m.key])})).filter(x=>x.value!=null),delta:m.value!=null&&m.mean!=null?m.value-m.mean:null}));
  const timeRows=p?[['混合','Mix_Start_TS','Mix_End_TS',null],['대기','Mix_End_TS','Hold_End_TS',a.synthetic?60:null],['여과','Filter_Start_TS','Filter_End_TS',null],['충전','Fill_Start_TS','Fill_End_TS',null]].map(([label,start,end,upper])=>{const actual=(Date.parse(p[end])-Date.parse(p[start]))/60000;return[label==='混合'?'혼합':label,p[start],p[end],actual,'미등록',upper,upper==null?null:Math.max(0,actual-upper)];}):[];
  return{bid,b,metrics,timeRows,raw:Object.fromEntries(V2.kinds.map(k=>[k,a.record[k]?[a.record[k]]:[]])),findings:a.findings.map(f=>({kind:f.kind,title:f.title,detail:f.current+' · '+f.basis,sources:[f.source]})),processRows:p?[['혼합 회전수 평균',number(p.Mix_RPM_Mean),'rpm',number(p.Mix_RPM_Setpoint),number(p.Mix_RPM_Mean)-number(p.Mix_RPM_Setpoint)],['혼합온도 평균',number(p.Mix_Temp_Mean_C),'°C',null,null],['혼합온도 최대',number(p.Mix_Temp_Max_C),'°C',null,null],['여과 차압 최대',number(p.Filter_DP_Max_kPa),'kPa',null,null]]:[],scopeNote:'요약 Checksheet는 원본 Batch_ID로 연결합니다. 공장 전체 교대 점검으로 임의 확대하지 않습니다.',synthetic:a.synthetic};
 }
 const a=V2.investigate(tables,bid,{scope:'SITE',type:'SHIFT_PRESTART'}),b=a.b;
 const refs=tables.Batch.rows.filter(r=>r.Batch_ID!==bid&&r.Reference_Eligible==='true'&&r.Disposition==='RELEASED'&&r.Product_ID===b.Product_ID&&r.Recipe_Rev===b.Recipe_Rev&&r.Data_Origin===b.Data_Origin&&Date.parse(r.End_TS)<Date.parse(b.Start_TS)).sort((a,b)=>Date.parse(a.End_TS)-Date.parse(b.End_TS));
 const metrics=a.qc.map(g=>{const q=g.final,points=[];if(q)for(const r of refs){const rows=tables.QC.byBatch[r.Batch_ID]||[];const matching=rows.filter(x=>x.Analyte_ID===q.Analyte_ID&&x.Is_Final==='true'&&x.Approval_Status==='APPROVED');if(matching.length!==1)continue;const x=matching[0];if(x.Qualifier==='EQ'&&x.Unit===q.Unit&&x.Method_ID===q.Method_ID&&x.Spec_Rev===q.Spec_Rev&&x.Data_Origin===q.Data_Origin&&V2.judgeQC(x,r.Data_Origin)==='규격 내')points.push({id:r.Batch_ID,value:number(x.Value)});}const value=q?.Qualifier==='EQ'?number(q.Value):null;return{label:g.id+(q?' ('+q.Unit+')':''),value,target:number(q?.Target),limit:q?[number(q.LSL),number(q.USL)]:null,points,...statistics(points,value)};});
 for(const m of metrics)if(m.n>=10&&Math.abs(m.z)>3)a.findings.push({kind:'signal',title:m.label+' 기준군 차이',detail:`현재 ${m.value}, 평균 ${m.mean.toFixed(3)}, 표준편차 ${m.sd.toFixed(3)}, ${m.z.toFixed(2)}s (탐색 신호)`,sources:[]});
 const timeRows=a.steps.map(s=>{const duration=(Date.parse(s.end)-Date.parse(s.start))/60000;const unique=k=>{const v=[...new Set(s.rows.map(r=>r[k]).filter(v=>v!=null&&v!==''))];return v.length===1?number(v[0]):null;};const target=unique('Target_Duration_min'),upper=unique('Upper_Duration_min');if(upper!=null&&duration>upper)a.findings.push({kind:'review',title:s.step+' 공정시간 초과',detail:`${duration}분 / 상한 ${upper}분 / 초과 ${duration-upper}분`,sources:s.rows.map(V2.source)});return[s.step,s.start,s.end,duration,target,upper,upper==null?null:Math.max(0,duration-upper)];});
 return{bid,b,metrics,timeRows,raw:a.records,findings:a.findings,processRows:a.process.map(g=>{const targets=[...new Set(g.rows.map(r=>r.Target_Value).filter(v=>v!=null&&v!==''))],target=targets.length===1?number(targets[0]):null;return[g.step+' / '+g.parameter+' 평균 (n='+g.count+')',g.mean,g.unit,target,target==null?null:g.mean-target];}),scopeNote:`공장 전체 교대 점검: 적용 ${a.check.required.length}건. 시간 유효구간으로 연결합니다.`,synthetic:b.Data_Origin==='SYNTHETIC'};
}
function renderFull(r){lastResult=r;$('#out').innerHTML='<section><h2>'+esc(r.bid)+' 제조 이력 보고서</h2><div class="row actions"><button id="exportHtml">HTML 보고서 저장</button><button id="printFull">인쇄 / PDF 저장</button></div><p class="muted">'+esc(r.b.Product_ID)+' / '+esc(r.b.Recipe_Rev)+' · '+esc(r.b.Start_TS)+' ~ '+esc(r.b.End_TS)+'</p><p>'+esc(r.scopeNote)+'</p>'+(r.synthetic?'':'')+'<h3>조사 결과 · '+r.findings.length+'건</h3>'+r.findings.map(f=>'<div class="finding"><b>'+esc(f.title)+'</b><p>'+esc(f.detail)+'</p><small>'+esc((f.sources||[]).join('; '))+'</small></div>').join('')+(r.findings.length?'':'<p>적용 가능한 규칙에서 추가 신호 없음</p>')+'</section><section><h3>QC · 목표값 및 과거 기준군 비교</h3><p class="muted">기준군: 동일 제품·처방·시험법·규격·단위, 이전 생산, Reference_Eligible=true 및 RELEASED인 비교 가능한 정상 결과. 평균은 목표값이 아닙니다. 표준편차 s는 n−1로 계산합니다.</p>'+grid(['항목','현재 값','목표값','목표값 대비 차이','기준 평균','평균 대비 차이','표준편차 s','평균에서 벗어난 정도 (표준편차 단위)','기준군 n','규격 하한 / 상한'],r.metrics.map(m=>[m.label,m.value,m.target==null?'미등록':m.target,m.value!=null&&m.target!=null?m.value-m.target:null,m.mean,m.delta,m.sd,m.z,m.n,m.limit?m.limit.map(v=>v==null?'없음':v).join(' / '):'미등록']))+'<p class="muted">n≥10 및 s>0에서 |편차|>3s를 탐색 신호로 표시합니다. 기준군 부족·s=0은 통계 판정 불가입니다. 관리도 판정이나 원인 확정이 아닙니다.</p></section><section><h3>QC 경향성</h3><p class="muted">생산 순서대로 정렬한 과거 기준군과 현재 Batch(빨강). 가로 간격은 Batch 순서이며 실제 시간 간격이 아닙니다. 점에 마우스를 올리면 Batch와 값이 표시됩니다.</p><div class="charts">'+r.metrics.map(m=>'<div><h4>'+esc(m.label)+'</h4>'+trend(m)+'<details><summary>비교군 '+m.n+'개</summary>'+esc(m.points.map(p=>p.id).join(', '))+'</details></div>').join('')+'</div></section><section><h3>공정 값과 설정 목표값</h3>'+grid(['항목','측정값','단위','등록 목표값','목표값 대비 차이'],r.processRows)+'</section><section><h3>공정 소요시간 및 초과시간</h3><p>총 제조시간 '+display((Date.parse(r.b.End_TS)-Date.parse(r.b.Start_TS))/60000)+'분</p>'+grid(['공정','시작','종료','실제 (분)','목표값 (분)','상한 (분)','상한 초과 (분)'],r.timeRows)+'<p class="muted">—는 기준 미등록 또는 계산 불가입니다. 시간 초과는 등록 상한 대비 계산하며, 상한을 목표값으로 해석하지 않습니다.</p></section><section><h3>연결 원본 기록</h3>'+Object.entries(r.raw).map(([k,rows])=>'<details><summary>'+k+' · '+rows.length+'건</summary>'+rows.map(row=>'<p>'+esc(row._file)+' · '+row._line+'행</p>'+grid(['열','값'],Object.entries(row).filter(([k])=>!k.startsWith('_')))).join('')+'</details>').join('')+'</section>';$('#printFull').onclick=()=>{document.querySelectorAll('#out details').forEach(d=>d.open=true);window.print();};$('#exportHtml').onclick=()=>{const clone=$('#out').cloneNode(true);clone.querySelectorAll('.actions').forEach(e=>e.remove());clone.querySelectorAll('details').forEach(d=>d.open=true);const text='<!doctype html><meta charset="utf-8"><title>'+esc(r.bid)+'</title><style>'+document.querySelector('style').textContent+'</style>'+clone.outerHTML;const url=URL.createObjectURL(new Blob([text],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Batch_Report_'+r.bid.replace(/[^a-z0-9_-]/gi,'_')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};}
load=async function(files){try{const next={...tables},old={...legacyTables},seen=new Set();for(const f of files){const raw=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer()),parsed=V2.parseCSV(raw);let k;const markers={Batch:'Product_ID',Material:'Material_Record_ID',Process:'Process_Record_ID',Equipment:parsed.headers.includes('Equipment_Event_ID')?'Equipment_Event_ID':'Equipment_Record_ID',QC:'QC_Record_ID',Checksheet:'Checksheet_Record_ID'};k=V2.kinds.find(n=>parsed.headers.includes(markers[n]));if(!k)throw Error(f.name+': 역할 식별 불가. 필수 식별 열을 확인하세요.');if(seen.has(k))throw Error(k+' 역할이 중복 선택되었습니다.');seen.add(k);const legacy=originalSchema[k].every(field=>parsed.headers.includes(field.name));if(legacy){old[k]=CMP.readTable(k,raw,originalSchema,f.name);const rows=legacyRows(k,parsed),h=schema[k].map(x=>x.name),csv=[h,...rows.map(r=>h.map(z=>r[z]))].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');next[k]=V2.readTable(k,csv,schema,f.name);next[k]._sourceCount=parsed.rows.length;}else{next[k]=V2.readTable(k,raw,schema,f.name);delete old[k];}}tables=next;legacyTables=old;refresh();$('#out').innerHTML='';msg('파일을 불러왔습니다. 상세 분석과 원본 기록을 함께 표시합니다.');}catch(e){msg(e.message,'bad');}};
$('#report').onclick=()=>{try{ensure();renderFull(analyze($('#bid').value.trim()));}catch(e){msg(e.message,'bad');}};
$('#scan').onclick=()=>{try{ensure();const bs=V2.filterBatches(tables.Batch.rows,$('#from').value,$('#to').value),results=bs.map(b=>analyze(b.Batch_ID)).filter(r=>r.findings.length);$('#out').innerHTML='<section><h2>날짜 범위 이상 Batch · '+results.length+'개</h2><p>규격·기록·공정시간·기준군 편차를 함께 조회합니다.</p>'+results.map((r,i)=>'<div class="finding"><button data-result="'+i+'">'+esc(r.bid)+'</button> '+r.findings.map(f=>esc(f.title)).join(', ')+'</div>').join('')+'</section>';document.querySelectorAll('[data-result]').forEach(e=>e.onclick=()=>{$('#bid').value=results[+e.dataset.result].bid;renderFull(results[+e.dataset.result]);});}catch(e){msg(e.message,'bad');}};
$('#demo').textContent='기본 표본 불러오기';$('#demo').onclick=async()=>{await load(Object.entries(LEGACY_SAMPLE).map(([k,v])=>new File([v],k+'.csv',{type:'text/csv'})));$('#bid').value='SIM-B046';};
const clearOriginal=$('#clear').onclick;$('#clear').onclick=()=>{legacyTables={};lastResult=null;clearOriginal();};
