(function(){
const standards=[
{id:'OCAP-DEMO-01',type:'OCAP',rev:'EXAMPLE-1',trigger:'규격 이탈 또는 공정 상한 초과',action:'원본·단위·규격 개정을 확인하고 영향 LOT의 식별 및 보류 여부를 품질 담당자에게 검토 요청한다. 승인된 절차에 따라 설비/원료/계측 이력을 확인한다. 재시험으로 최초 이탈 기록을 지우지 않는다.',result:'영향 LOT 목록, 원본 시험기록, 계측 확인, 처분 승인 근거',owner:'공정 엔지니어 / 품질 담당자'},
{id:'OCAP-DEMO-02',type:'OCAP',rev:'EXAMPLE-1',trigger:'기록 누락·연결 오류',action:'동일 Batch와 시간 범위로 원본 시스템을 재조회한다. 설비·시험법·유효시간을 대조하고 누락과 실제 미수행을 구분한다.',result:'재추출 범위, 확보 기록, 미확보 사유, 판단 제한',owner:'데이터 담당 / 공정 엔지니어'},
{id:'OCAP-DEMO-03',type:'OCAP',rev:'EXAMPLE-1',trigger:'통계 변화 또는 등록 능력 기준 미달',action:'측정시스템·시간순 안정성·설비·원료 등 다른 요인의 영향을 검토한다. 근거가 있는 원인 가설별 확인 시험을 설계하고 승인 후 수행한다.',result:'가설, 지지·반증 자료, 확인시험 계획, 실시 결과',owner:'공정 엔지니어 / 품질 담당자'},
{id:'FMEA-DEMO-01',type:'FMEA',rev:'EXAMPLE-1',trigger:'혼합·여과·QC 이상 검토',action:'잠재 고장 형태: 혼합조건 이탈 또는 여과 저항 증가. 잠재 영향: 제품 특성 변동. 잠재 원인: 설정·필터 상태·측정 오류 등 미검증 가설. 현재 예방/검출 통제를 대조하고 평가팀이 위험도를 결정한다.',result:'고장 형태·영향·원인 가설, 현재 통제, 증거, 개선안, S/O/D 평가 근거 (미평가 값은 비워둠)',owner:'다기능 FMEA 검토팀'},
{id:'CP-DEMO-01',type:'Control Plan',rev:'EXAMPLE-1',trigger:'조치 후 검증 및 지속 수집',action:'제품·특성·단위·시험법·규격 개정별 측정 계획을 등록한다. Batch별 QC 최종값과 설비/교대 점검을 수집한다. 관찰기간·표본수·판정 기준을 사전 합의하고 동일 조건으로 전후 결과를 검토한다.',result:'수집 범위, 측정 책임자, 빈도, 반응계획, 전후 데이터, 효과성 판정과 검토자',owner:'공정 엔지니어 / 품질 담당자'}];
standards.push(...CMPKnowledge.documents());
let snapshot=null;const key='cmp-review-cases-v1';let cases=[];try{cases=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(cases))cases=[];}catch{}
const safe=v=>esc(v),num=v=>Number.isFinite(v)?display(v):'계산 불가';
function invalidate(){snapshot=null;document.querySelector('#rcaPanel')?.remove();}
function summaries(s){const lines=[],c=s.c;lines.push(`분석 조건의 유효 Batch ${c.n}개, Y 평균 ${num(c.mean)}, 전체 표준편차 ${num(c.overall)}입니다.`);if(c.lsl!=null||c.usl!=null)lines.push(`등록 규격(${s.basis}) 대비 ${c.outside.length}/${c.n}개 Batch가 이탈했습니다. 이는 선택한 분석 집단의 결과입니다.`);
if(s.methods.includes('cap')){for(const metric of ['Cpk','Ppk']){if(Number.isFinite(c[metric]))lines.push(s.threshold!=null?`${metric}=${num(c[metric])}, 사용자 등록 기준 ${num(s.threshold)}(${s.thresholdBasis})에 ${c[metric]<s.threshold?'미달':'이상'}입니다. 분포·안정성 미검증 상태의 탐색 추정치입니다.`:`${metric}=${num(c[metric])}입니다. 내부 관리 기준 미등록으로 충족 여부는 판정하지 않았습니다.`);}}
if(s.reg)lines.push(`X–Y 분석 가능한 X·Y 쌍 ${s.reg.n}개, R²=${num(s.reg.r2)}입니다. 이 표본의 선형 모형 설명력이며 불량 원인일 확률이나 직접 기여의 증거가 아닙니다. 다른 요인의 영향과 예측 오차를 검토한 후 확인시험이 필요합니다.`);
const eq=[...new Set(s.rows.map(r=>r.equipment))].map(id=>{const rs=s.rows.filter(r=>r.equipment===id),fail=rs.filter(r=>(c.lsl!=null&&r.y<c.lsl)||(c.usl!=null&&r.y>c.usl)).length;return{id,n:rs.length,fail,sd:CMPStats.sd(rs.map(r=>r.y))};});
if(eq.length>1&&(c.lsl!=null||c.usl!=null)){const sorted=[...eq].sort((a,b)=>b.fail/b.n-a.fail/a.n);if(sorted[0].fail&&sorted[0].fail/sorted[0].n>sorted[1].fail/sorted[1].n)lines.push(`${sorted[0].id}의 관측 이탈률이 비교 설비 중 가장 높습니다 (${sorted[0].fail}/${sorted[0].n}). 표본수·생산시점·원료 조건을 대조한 뒤 해당 설비의 점검 이력을 우선 확인하도록 권장합니다. 설비 원인으로 확정하지 않습니다.`);}
return lines;}
function accept(ctx){const threshold=number(document.querySelector('#reviewThreshold')?.value),thresholdBasis=document.querySelector('#reviewThresholdBasis')?.value.trim()||'';if(threshold!=null&&(!(threshold>0)||!thresholdBasis))throw Error('능력 기준을 입력하면 양수와 기준 근거를 함께 등록하세요.');const lookup=new Map(ctx.xs.rows.map(r=>[r.id,r.y]));let reg=null;if(ctx.methods.includes('xy'))try{reg=CMPStats.regression(ctx.rows.filter(r=>lookup.has(r.id)).map(r=>({...r,x:lookup.get(r.id)})));}catch{}
 snapshot={...ctx,label:ctx.s.label,xLabel:ctx.xs.label,basis:$('#statBasis').value,threshold,thresholdBasis,reg,created:new Date().toISOString(),sourceFiles:Object.fromEntries(V2.kinds.map(k=>[k,{name:tables[k].filename,rows:tables[k].rows.length}])),sources:ctx.rows.map(r=>({batch:r.id,records:['Batch','QC','Process'].flatMap(k=>(tables[k].byBatch[r.id]||[]).map(x=>({table:k,file:x._file,line:x._line,record:x}))) }))};snapshot.summary=summaries(snapshot);return '<section id="evidenceSummary"><h3>근거 기반 요약 및 검토 의견</h3><ul>'+snapshot.summary.map(t=>'<li>'+safe(t)+'</li>').join('')+'</ul><p class="muted">규칙 기반 문장 생성 · 원인 확정/자동 출하 판정 없음. 분석 조건을 변경하면 이 요약은 무효화됩니다.</p></section>';}
const setupBefore=StatsVisual.setup;StatsVisual.setup=function(panel){setupBefore(panel);const block=document.createElement('div');block.className='row';block.innerHTML='<label>내부 Cpk/Ppk 최소 기준 (선택)<input id="reviewThreshold" type="number" min="0" step="any" placeholder="미등록 시 충족 여부 판정 안 함"></label><label>내부 기준 근거<input id="reviewThresholdBasis" placeholder="예: 사내 기준 CP-01 Rev.2"></label>';panel.querySelector('#statRun').parentElement.before(block);panel.addEventListener('input',invalidate);};
function docHTML(doc){return '<h2>'+safe(doc.type)+' 예시 '+safe(doc.id)+'</h2><p>개정 '+doc.rev+'</p>'+grid(['항목','내용'],[['적용 신호',doc.trigger],['제안 조치',doc.action],['요구 결과/증거',doc.result],['담당 역할',doc.owner],...(doc.kb?[["확인시험",doc.verification],["관리 특성",doc.control],["수집 시점",doc.frequency],["판정 기준",doc.criterion],["문헌 해석 범위",doc.sourceScope]]:[]),['적용 조건','현장 승인 절차·규격·책임자 확인 후 사용. 자동 조작·출하 승인 없음.']])+(doc.evidence?'<h4>근거 자료</h4>'+doc.evidence.map(e=>'<p><a href="'+safe(e.url)+'" target="_blank" rel="noopener">'+safe(e.title)+'</a><br>'+safe(e.fact)+'</p>').join(''):'');}
function download(name,text,type='text/html;charset=utf-8'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([type.startsWith('text/html')?editableDocument(text):text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function wrap(title,body){return '<!doctype html><html lang="ko"><meta charset="utf-8"><title>'+safe(title)+'</title><style>body{font:15px Malgun Gothic,sans-serif;max-width:1050px;margin:30px auto;line-height:1.7}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccd5dc;padding:10px;text-align:left}h1,h2{color:#163449}textarea{width:100%}</style><body>'+body+'</body></html>';}
function open(){try{ensure();const bid=$('#bid').value.trim(),r=analyze(bid);let linked=snapshot?.rows.some(x=>x.id===bid)?snapshot:null;const findings=r.findings,ids=new Set();if(findings.some(f=>f.kind==='oos'||(f.kind==='review'&&/초과|온도 검토|차압 검토|대기시간 연장/.test(f.title))))ids.add('OCAP-DEMO-01');if(findings.some(f=>f.kind==='missing'||f.kind==='integrity'))ids.add('OCAP-DEMO-02');if(findings.some(f=>f.kind==='signal'||f.kind==='change')||(linked&&(linked.c.signals.length||linked.c.outside.length||linked.threshold!=null&&['Cpk','Ppk'].some(k=>Number.isFinite(linked.c[k])&&linked.c[k]<linked.threshold))))ids.add('OCAP-DEMO-03');if(ids.has('OCAP-DEMO-01')||ids.has('OCAP-DEMO-03'))ids.add('FMEA-DEMO-01');if(ids.size)ids.add('CP-DEMO-01');for(const c of CMPKnowledge.cases)if(CMPKnowledge.matches(c,r).length)for(const type of ['OCAP','FMEA','CP'])ids.add(type+'-REF-'+c.id);const matched=standards.filter(s=>ids.has(s.id));
document.querySelector('#rcaPanel')?.remove();const panel=document.createElement('section');panel.id='rcaPanel';panel.innerHTML='<h2>3단계 · RCA 지원 / 4단계 · 검증과 지속 수집</h2><p>대상 Batch: <b>'+safe(bid)+'</b> · 원인·조치 결과는 엔지니어 검토 전 미확정입니다.</p>'+(snapshot&&!linked?'<p>현재 통계 집단에 이 Batch가 없어 통계 결과를 초안에서 제외합니다.</p>':'')+'<h3>적용 문서 · 조치 및 확인 결과</h3><p>문서 연결은 현재 Batch의 신호와 연결된 통계 집단 신호에 대한 예시 규칙입니다. 집단의 이탈이나 능력 부족을 이 Batch의 불량 원인으로 간주하지 않습니다.</p>'+(matched.length?matched.map(s=>'<details open><summary>'+safe(s.id)+' · '+safe(s.type)+'</summary>'+docHTML(s)+'</details>').join(''):'<p>등록된 규칙에서 적용 신호가 없어 조치를 생성하지 않았습니다.</p>')+'<details><summary>예시 표준문서 전체 보기 / 다운로드</summary>'+standards.map((s,i)=>docHTML(s)+'<button data-standard="'+i+'">편집용 예시 HTML 저장</button>').join('')+'</details><h3>검증 기록 (사용자 입력)</h3><div class="row"><label>담당자<input id="rcaOwner"></label><label>검증 기한<input id="rcaDue" type="date"></label><label>상태<select id="rcaState"><option>제안</option><option>진행 중</option><option>검증 완료</option></select></label></div><label>원인 가설 / 원인을 지지하거나 배제할 자료와 확인시험<textarea id="rcaHypothesis" rows="3"></textarea></label><label>실제 실시 조치 및 결과<textarea id="rcaResult" rows="3"></textarea></label><label>증거 문서 번호·측정 결과·검토자<textarea id="rcaEvidence" rows="3"></textarea></label><label>지속 수집 계획 (특성·빈도·기간·표본수·효과성 기준)<textarea id="rcaPlan" rows="3"></textarea></label><p><button id="rcaSave">검증 기록과 근거 분석 시점 기록 저장</button> <button id="rcaDraft">엔지니어 검토 초안 생성</button> <button id="rcaHistory">지속 수집 이력 내보내기</button></p><p id="rcaMessage" role="status"></p><p>이 브라우저의 저장 이력 <span id="reviewCount">'+cases.length+'</span>건. CSV 재조회 후 2단계 분석과 검증 기록을 다시 저장하면 새 시점의 이력을 누적합니다. MES/SPC 자동 연결은 아직 없으며 브라우저 저장 삭제에 대비해 이력을 내보내세요.</p><div id="draftArea"></div>';$('#out').prepend(panel);panel.querySelectorAll('[data-standard]').forEach(b=>b.onclick=()=>download(standards[+b.dataset.standard].id+'.html',wrap('예시 표준', '<main contenteditable="true">'+docHTML(standards[+b.dataset.standard])+'</main>')));
const input=()=>({owner:$('#rcaOwner').value.trim(),due:$('#rcaDue').value,state:$('#rcaState').value,hypothesis:$('#rcaHypothesis').value.trim(),result:$('#rcaResult').value.trim(),evidence:$('#rcaEvidence').value.trim(),plan:$('#rcaPlan').value.trim()});
const base=()=>({format:'CMP-REVIEW-1',id:crypto.randomUUID(),saved:new Date().toISOString(),bid,report:r,analysis:linked,standards:matched.map(s=>({...s})),user:input()});
$('#rcaSave').onclick=()=>{try{const entry=base();if(entry.user.state==='검증 완료'&&(!entry.user.owner||!entry.user.result||!entry.user.evidence))throw Error('검증 완료에는 담당자·실시 결과·증거/검토자가 필요합니다.');const next=[...cases,entry];localStorage.setItem(key,JSON.stringify(next));cases=next;document.querySelector('#reviewCount').textContent=cases.length;$('#rcaMessage').textContent='저장 완료 · '+cases.length+'건. 검증 상태는 사용자 입력이며 프로그램이 효과성을 인증하지 않습니다.';}catch(e){$('#rcaMessage').textContent='저장 실패: '+e.message;}};
$('#rcaHistory').onclick=()=>download('CMP_Review_History.json',JSON.stringify(cases,null,2),'application/json');
$('#rcaDraft').onclick=()=>{const e=base(),u=e.user;if(u.state==='검증 완료'&&(!u.owner||!u.result||!u.evidence)){document.querySelector("#rcaMessage").textContent='검증 완료에는 담당자·실시 결과·증거/검토자가 필요합니다.';return;}let body='<h1>제조 이력 및 RCA 엔지니어 검토 초안</h1><p>Batch '+safe(bid)+' · '+safe(e.saved)+' · 작성 지원: 김태양 · Ver1.0 · 엔지니어 승인 전 초안</p><h2>제조 이력에서 확인한 사실</h2>'+grid(['제품','처방','설비','시작','종료'],[[r.b.Product_ID,r.b.Recipe_Rev,r.b.Equipment_ID,r.b.Start_TS,r.b.End_TS]]);if(findings.length)body+=grid(['확인 신호','근거','원본 위치'],findings.map(f=>[f.title,f.detail,(f.sources||[]).join('; ')]));if(linked)body+='<h2>통계 요약 및 검토 의견</h2><p>Y: '+safe(linked.label)+' / X: '+safe(linked.xLabel)+'</p><p>규격: '+safe(linked.basis||'미등록')+' / LSL '+num(linked.c.lsl)+' / USL '+num(linked.c.usl)+' / 내부 기준 '+num(linked.threshold)+' '+safe(linked.thresholdBasis)+'</p><ul>'+linked.summary.map(t=>'<li>'+safe(t)+'</li>').join('')+'<details><summary>통계에 사용한 Batch 및 원본 위치</summary>'+grid(['Batch','출처'],linked.sources.map(s=>[s.batch,s.records.map(x=>x.file+':'+x.line).join('; ')]))+'</details>';if(matched.length)body+='<h2>제안 조치와 요구 증거</h2>'+grid(['예시 문서 / 개정','제안 조치','필요한 결과·증거'],matched.map(s=>[s.id+' / '+s.rev,s.action,s.result]));for(const[k,title]of [['hypothesis','사용자 입력 원인 가설 및 확인시험'],['result','사용자 입력 실시 조치와 결과'],['evidence','사용자 입력 증거 및 검토자'],['plan','지속 수집 및 효과성 확인 계획']])if(u[k])body+='<h2>'+title+'</h2><p>'+safe(u[k]).replaceAll('\n','<br>')+'</p>';if(u.owner)body+='<p>담당자: '+safe(u.owner)+(u.due?' · 기한: '+safe(u.due):'')+'</p>';body+='<p>조치 상태 (사용자 입력): '+safe(u.state)+'</p>';$('#draftArea').innerHTML='<h3>검토 초안 편집</h3><p>아래 내용을 직접 수정한 뒤 저장하세요. 자동 생성 근거와 사용자 수정본은 검증 기록 분석 시점 기록과 별도로 관리됩니다.</p><div id="draftEditor" contenteditable="true" style="border:1px solid #9babb8;padding:16px;background:white">'+body+'</div><p><button id="draftExport">편집 가능한 HTML 문서 저장</button></p>';$('#draftExport').onclick=()=>download('Engineer_Review_'+bid.replace(/[^a-z0-9_-]/gi,'_')+'.html',wrap('엔지니어 검토 초안','<p>이 문서는 브라우저에서 본문을 편집할 수 있습니다. 편집 후 상단 수정본 HTML 저장 버튼을 누르세요.</p><main contenteditable="true">'+$('#draftEditor').innerHTML+'</main>'));};panel.scrollIntoView({behavior:'smooth'});
}catch(e){msg(e.message,'bad');}}
const button=document.createElement('button');button.id='rcaOpen';button.textContent='3단계 · RCA / 검증';$('#report').parentElement.append(button);button.onclick=open;
const oldLoad=load;load=async function(files){invalidate();await oldLoad(files);};const oldClear=$('#clear').onclick;$('#clear').onclick=()=>{invalidate();oldClear();};
window.CMPReview={accept,invalidate,standards,getCases:()=>JSON.parse(JSON.stringify(cases)),mergeCases:incoming=>{const next=[...cases];for(const e of incoming){const old=next.find(x=>x.id===e.id);if(old&&JSON.stringify(old)!==JSON.stringify(e))throw Error('동일 기록 ID의 내용이 다릅니다. 복원을 중단했습니다.');if(!old)next.push(e);}localStorage.setItem(key,JSON.stringify(next));cases=next;invalidate();return cases.length;}};
})();
