(function(root){
const quantile=(values,p)=>{const a=[...values].sort((a,b)=>a-b),i=(a.length-1)*p,lo=Math.floor(i);return a[lo]+(a[Math.ceil(i)]-a[lo])*(i-lo);};
function summary(rows){const v=rows.map(r=>r.y),q1=quantile(v,.25),median=quantile(v,.5),q3=quantile(v,.75),iqr=q3-q1,inner=v.filter(x=>x>=q1-1.5*iqr&&x<=q3+1.5*iqr);return{n:v.length,min:Math.min(...v),max:Math.max(...v),q1,median,q3,iqr,low:Math.min(...inner),high:Math.max(...inner),outliers:rows.filter(r=>r.y<q1-1.5*iqr||r.y>q3+1.5*iqr)};}
function histogram(values,count){const min=Math.min(...values),max=Math.max(...values),lo=min===max?min-.5:min,hi=min===max?max+.5:max,bins=Array.from({length:count},(_,i)=>({lo:lo+(hi-lo)*i/count,hi:lo+(hi-lo)*(i+1)/count,n:0}));values.forEach(v=>bins[Math.min(count-1,Math.max(0,Math.floor((v-lo)/(hi-lo)*count)))].n++);return bins;}
function wilson(fail,n){if(!n)return[null,null];const z=1.95996398454,p=fail/n,d=1+z*z/n,mid=(p+z*z/(2*n))/d,half=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return[Math.max(0,mid-half),Math.min(1,mid+half)];}
const groups=rows=>[...new Set(rows.map(r=>r.equipment))].map(name=>({name,rows:rows.filter(r=>r.equipment===name)}));
const choices=[['hist','Histogram','전체 분포·치우침과 규격 위치'],['box','Box Plot · 설비별','중앙값·산포·통계적 이상점 비교'],['trend','시간순 추세','시간에 따른 변화와 관심 LOT 위치'],['scatter','X–Y 산점도','인자 간 관계와 단순 회귀선'],['residual','잔차 vs 예측값','회귀의 곡선 패턴·불균일 산포 확인'],['imr','I–MR 관리도','동일 설비의 수준·변동 변화'],['lag','Lag-1 Plot','직전 Batch와의 이전 Batch와의 연관성 확인'],['pareto','규격 이탈 Pareto','설비별 이탈 건수 우선순위와 이탈률']];
function setup(panel){
 const methods=panel.querySelector('[name=statMethod]').parentElement.parentElement,desc={cap:['공정능력','Cp/Cpk/Cpu/Cpl · Pp/Ppk/Ppu/Ppl','규격 입력, Cpk는 군내 추정 검토 필요'],xy:['인자 관계','Pearson/Spearman · 회귀 R²','같은 Batch의 X·Y 수치 쌍'],dist:['분포·그래프','선택한 그래프 및 분포표','아래에서 발표에 필요한 그림 선택'],vc:['분산성분','설비 간 %Contribution','설비를 더 큰 집단의 표본으로 보는 가정 확인 필요']};
 const table=document.createElement('table');table.className='analysis-options';table.innerHTML='<caption>분석 항목 선택</caption><thead><tr><th>선택 / 분석</th><th>제공 내용</th><th>필요 조건</th></tr></thead><tbody>'+Object.entries(desc).map(([id,[name,detail,need]])=>'<tr><td><label class="check-row"><input type="checkbox" name="statMethod" value="'+id+'" '+(id==='vc'?'':'checked')+'>'+name+'</label></td><td>'+detail+'</td><td>'+need+'</td></tr>').join('')+'<tr><td><label class="check-row"><input type="checkbox" name="statMethod" value="diag" checked>공정 진단</label></td><td>중앙값·IQR, 실측 이탈률·95% 구간, 설비별 비교</td><td>규격 미등록 시 이탈률은 계산하지 않음</td></tr></tbody>';methods.replaceWith(table);
 const graphs=document.createElement('div');graphs.innerHTML='<h3>그래프 선택</h3><p class="muted">분석 수치와 그래프는 따로 선택할 수 있습니다. 선택한 그림은 결과 HTML에 포함되며 SVG로도 저장할 수 있습니다.</p><table class="analysis-options"><thead><tr><th>선택 / 그래프</th><th>확인할 내용</th></tr></thead><tbody>'+choices.map(([id,name,why])=>'<tr><td><label class="check-row"><input type="checkbox" name="statGraph" value="'+id+'" '+(['hist','box','trend','scatter'].includes(id)?'checked':'')+'>'+name+'</label></td><td>'+why+'</td></tr>').join('')+'</tbody></table><div class="row"><label>Histogram 구간 수<select id="statBins"><option>5</option><option selected>10</option><option>15</option><option>20</option><option>30</option></select></label></div>';table.after(graphs);
 for(const id of ['statAssume','statRandom'])panel.querySelector('#'+id).parentElement.classList.add('check-row','assumption-row');
 const basis=panel.querySelector('#statBasis');basis.placeholder='예: 제품 규격서 QC-001 Rev.3';basis.setAttribute('aria-describedby','specHelp');const help=document.createElement('p');help.id='specHelp';help.className='muted';help.textContent='규격 출처 / 개정 = 상·하한의 근거 문서와 버전입니다. 예: 고객 승인 규격 QC-001 Rev.3. 입력한 근거는 결과 보고서에 함께 저장합니다.';basis.parentElement.parentElement.after(help);
}
let clipSequence=0;
function chart(title,xlabel,ylabel,points,{line=false,refs=[],fit=null,bars=false,rangeX=null,rangeY=null,categories=false}={}){
 if(!points.length)return '<p>표시할 값이 없습니다.</p>';const xx=points.map(p=>p.x),yy=points.map(p=>p.y).concat(refs.filter(r=>r.axis==='y').map(r=>r.value));if(bars)xx.push(...points.flatMap(p=>[p.lo,p.hi]));xx.push(...refs.filter(r=>r.axis==='x').map(r=>r.value));if(fit)yy.push(...[Math.min(...xx),Math.max(...xx)].map(x=>fit.intercept+fit.slope*x));
 const span=(a,forced)=>{if(forced)return forced;const min=Math.min(...a),max=Math.max(...a),pad=(max-min)*.07||.5;return[min-pad,max+pad];},xr=span(xx,rangeX),yr=span(yy,rangeY),x=v=>76+(v-xr[0])/(xr[1]-xr[0]||1)*660,y=v=>292-(v-yr[0])/(yr[1]-yr[0]||1)*230;
 const clip='cmp-plot-'+(++clipSequence);let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 820 380" role="img" aria-label="'+esc(title)+'"><rect width="820" height="380" fill="white"/><text x="76" y="24" font-size="16" fill="#182d45">'+esc(title)+'</text>';
 for(let i=0;i<=4;i++){const vx=xr[0]+(xr[1]-xr[0])*i/4,vy=yr[0]+(yr[1]-yr[0])*i/4;svg+='<path d="M76 '+y(vy)+' H736 M'+x(vx)+' 62 V292" stroke="#cbd5df" stroke-dasharray="3 4"/><text x="70" y="'+(y(vy)+4)+'" text-anchor="end" font-size="11">'+display(vy)+'</text><text x="'+x(vx)+'" y="311" text-anchor="middle" font-size="11">'+display(vx)+'</text>';}
 refs.forEach(r=>{const pos=r.axis==='x'?x(r.value):y(r.value);svg+='<path d="'+(r.axis==='x'?'M'+pos+' 62 V292':'M76 '+pos+' H736')+'" stroke="'+(r.color||'#b84046')+'" stroke-dasharray="7 4"/><text x="'+(r.axis==='x'?Math.max(115,Math.min(690,pos)):730)+'" y="'+(r.axis==='x'?45:pos-5)+'" text-anchor="end" font-size="10">'+esc(r.label)+' '+display(r.value)+'</text>';});
 svg+='<defs><clipPath id="'+clip+'"><rect x="76" y="62" width="660" height="230"/></clipPath></defs><g class="plot-marks" clip-path="url(#'+clip+')">';if(bars)points.forEach(p=>{svg+='<rect x="'+x(p.lo)+'" y="'+y(p.y)+'" width="'+Math.max(1,x(p.hi)-x(p.lo)-2)+'" height="'+Math.max(0,y(0)-y(p.y))+'" fill="#12867d"><title>'+esc(p.id)+'</title></rect>';});
 else {if(line)svg+='<polyline points="'+points.map(p=>x(p.x)+','+y(p.y)).join(' ')+'" fill="none" stroke="#16867c" stroke-width="1.5"/>';svg+=points.map(p=>'<circle cx="'+x(p.x)+'" cy="'+y(p.y)+'" r="3.5" fill="'+(p.highlight?'#c23940':'#087f78')+'"><title>'+esc(p.id)+': X='+display(p.x)+', Y='+display(p.y)+'</title></circle>').join('');}
 if(fit)svg+='<path d="M'+x(xr[0])+' '+y(fit.intercept+fit.slope*xr[0])+' L'+x(xr[1])+' '+y(fit.intercept+fit.slope*xr[1])+'" stroke="#98529f" stroke-width="2"/>';
 svg+='</g>';if(categories){svg=svg.replace(/<text x="[^"]+" y="311"[^>]*>[^<]*<\/text>/g,'');svg+=points.map(p=>'<text x="'+x(p.x)+'" y="315" text-anchor="middle" font-size="12">'+esc(p.id)+'</text>').join('');}return svg+'<text x="406" y="346" text-anchor="middle" font-size="12">'+esc(xlabel.length>85?xlabel.slice(0,82)+'…':xlabel)+'</text><text x="76" y="366" font-size="12">Y: '+esc(ylabel.length>90?ylabel.slice(0,87)+'…':ylabel)+'</text></svg>';
}
function boxes(rows,label){const gs=groups(rows),stats=gs.map(g=>({...g,...summary(g.rows)})),min=Math.min(...rows.map(r=>r.y)),max=Math.max(...rows.map(r=>r.y)),pad=(max-min)*.1||1,y=v=>285-(v-min+pad)/(max-min+2*pad)*225,w=Math.max(820,gs.length*140+130);let out='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+w+' 360" role="img" aria-label="설비별 Box Plot"><rect width="100%" height="100%" fill="white"/><text x="70" y="25" font-size="16">설비별 Box Plot</text>';
 for(let i=0;i<=4;i++){const v=min-pad+(max-min+2*pad)*i/4;out+='<path d="M70 '+y(v)+' H'+(w-30)+'" stroke="#cbd5df" stroke-dasharray="3 4"/><text x="60" y="'+y(v)+'" text-anchor="end" font-size="11">'+display(v)+'</text>';}
 stats.forEach((g,i)=>{const x=120+(i+.5)*(w-170)/stats.length;out+='<path d="M'+x+' '+y(g.low)+' V'+y(g.high)+' M'+(x-22)+' '+y(g.low)+' h44 M'+(x-22)+' '+y(g.high)+' h44" stroke="#087f78"/><rect x="'+(x-32)+'" y="'+y(g.q3)+'" width="64" height="'+Math.max(1,y(g.q1)-y(g.q3))+'" fill="#c4e8e1" stroke="#087f78"/><path d="M'+(x-32)+' '+y(g.median)+' h64" stroke="#152b40" stroke-width="3"/><text x="'+x+'" y="312" text-anchor="middle">'+esc(g.name)+'</text><text x="'+x+'" y="330" text-anchor="middle" font-size="11">n='+g.n+'</text>'+g.outliers.map(r=>'<circle cx="'+x+'" cy="'+y(r.y)+'" r="4" fill="#c23940"><title>'+esc(r.id)+': '+r.y+'</title></circle>').join('');});return out+'<text x="70" y="353" font-size="12">Y: '+esc(label)+'</text></svg>'+grid(['설비','n','최소','Q1','중앙값','Q3','최대','1.5 IQR 밖'],stats.map(g=>[g.name,g.n,g.min,g.q1,g.median,g.q3,g.max,g.outliers.length]));}
function diagnostics(rows,c){const s=summary(rows),hasSpec=c.lsl!=null||c.usl!=null,rate=c.outside.length/rows.length,ci=wilson(c.outside.length,rows.length);return '<h3>추가 공정 진단</h3>'+grid(['중앙값','IQR','최소','최대','실측 규격 이탈률 %','95% 구간 %'],[[s.median,s.iqr,s.min,s.max,hasSpec?rate*100:null,hasSpec?ci.map(v=>display(v*100)).join(' ~ '):'규격 미등록']])+'<p>이탈률은 이번 Y의 유효 Batch 기준이며 공장 전체 불량률이나 예측 DPMO가 아닙니다. 95% Wilson 구간은 독립적인 이항 관측을 가정합니다.</p>'+grid(['설비','n','평균','표준편차','중앙값','규격 이탈 수','이탈률 %'],groups(rows).map(g=>{const n=g.rows.filter(r=>(c.lsl!=null&&r.y<c.lsl)||(c.usl!=null&&r.y>c.usl)).length;return[g.name,g.rows.length,CMPStats.mean(g.rows.map(r=>r.y)),CMPStats.sd(g.rows.map(r=>r.y)),summary(g.rows).median,hasSpec?n:null,hasSpec?n/g.rows.length*100:null];}));}
function render({rows,c,s,xs,target}){const selected=[...document.querySelectorAll('[name=statGraph]:checked')].map(e=>e.value),lookup=new Map(xs.rows.map(r=>[r.id,r.y])),pairs=rows.filter(r=>lookup.has(r.id)).map(r=>({...r,x:lookup.get(r.id)})),refs=[['LSL',c.lsl],['USL',c.usl],['목표값',target]].filter(([,v])=>v!=null).map(([label,value])=>({label,value,axis:'x'}));let html='';
 const add=(id,title,why,body)=>{html+='<section class="stat-figure" data-graph="'+id+'"><h3>'+title+'</h3><p>'+why+'</p><div class="figure-scroll">'+body+'</div><button class="save-figure" type="button">그림 SVG 저장</button></section>';};
 for(const id of selected){try{
 if(id==='hist'){const bins=histogram(rows.map(r=>r.y),+$('#statBins').value);add(id,'Histogram · 선택 Y의 분포','막대는 구간별 Batch 수입니다. 규격선 밖 데이터와 치우침을 확인하세요. 분포 모양만으로 정규성을 확정하지 않습니다.',chart('Histogram','Y 측정값','Batch 수',bins.map(b=>({x:(b.lo+b.hi)/2,y:b.n,lo:b.lo,hi:b.hi,id:display(b.lo)+' ~ '+display(b.hi)+' : '+b.n})),{bars:true,refs,rangeY:[0,Math.max(1,...bins.map(b=>b.n))*1.12]})+'<details><summary>구간별 수치</summary>'+grid(['이상','미만 (마지막 이하)','개수'],bins.map(b=>[b.lo,b.hi,b.n]))+'</details>');}
 if(id==='box')add(id,'Box Plot · 설비별 비교','상자는 Q1~Q3, 굵은 선은 중앙값입니다. 수염은 1.5×IQR 안의 관측 범위, 빨간 점은 그 밖의 값입니다. 통계적 이상점은 규격 불량과 다릅니다. 사분위수는 선형보간 방식입니다.',boxes(rows,s.label));
 if(id==='trend')add(id,'시간순 추세','X축은 시간순 Batch 순번입니다. 점에 마우스를 올리면 Batch_ID와 값을 확인합니다. 설비가 섞여 있으면 설비 필터로 나누어 보세요.',chart('시간순 추세','시간순 Batch 순번',s.label,rows.map((r,i)=>({x:i+1,y:r.y,id:r.id,highlight:r.id===$('#statFocus').value})),{line:true,refs:refs.map(r=>({...r,axis:'y'})).concat([{axis:'y',value:c.mean,label:'평균',color:'#657c8d'}])}));
 if(id==='scatter'||id==='residual'){const reg=CMPStats.regression(pairs);add(id,id==='scatter'?'X–Y 산점도와 회귀선':'잔차 vs 예측값',id==='scatter'?'점은 동일 Batch의 X·Y입니다. 보라색 선은 단순 선형 회귀입니다. 관계가 원인을 확정하지 않습니다.':'잔차=관측 Y−예측 Y. 곡선 패턴이나 부채꼴 산포가 있으면 선형성·예측값에 따라 오차 크기가 일정한지을 재검토하세요.',chart(id==='scatter'?'X–Y 산점도':'잔차 vs 예측값',id==='scatter'?xs.label:'예측 Y',id==='scatter'?s.label:'잔차',id==='scatter'?pairs:reg.residuals.map(r=>({...r,x:reg.intercept+reg.slope*r.x,y:r.residual})),id==='scatter'?{fit:reg}:{refs:[{axis:'y',value:0,label:'0'}]}));}
 if(id==='imr'){if(!(c.within>0))throw Error('설비 1개와 MR 추정법·적용성 확인을 선택하세요. 변동 0이면 한계 추정 불가입니다.');const mrMean=CMPStats.mean(c.mr),mrMax=3.267*mrMean;add(id,'I–MR 관리도','규격선이 아닌 공정 관리한계입니다. I 한계=평균±3σwithin, MR 상한=3.267×MR 평균. 같은 자료로 한계를 추정한 탐색 차트이며 전체 이상 규칙을 적용한 안정성 판정은 아닙니다.',chart('I 관리도','시간순 Batch 순번',s.label,rows.map((r,i)=>({x:i+1,y:r.y,id:r.id,highlight:Math.abs(r.y-c.mean)>3*c.within})),{line:true,refs:[{axis:'y',value:c.mean,label:'CL'},{axis:'y',value:c.mean+3*c.within,label:'UCL'},{axis:'y',value:c.mean-3*c.within,label:'LCL'}]})+chart('MR 관리도','후행 Batch 순번','인접 값 차이의 절댓값',c.mr.map((v,i)=>({x:i+2,y:v,id:rows[i].id+' → '+rows[i+1].id,highlight:v>mrMax})),{line:true,refs:[{axis:'y',value:mrMean,label:'CL'},{axis:'y',value:mrMax,label:'UCL'},{axis:'y',value:0,label:'LCL'}]})+'<p>I 단일점 신호 '+c.imrSignals.length+'건 / MR 상한 초과 '+c.mr.filter(v=>v>mrMax).length+'건</p>');}
 if(id==='lag'){if(new Set(rows.map(r=>r.equipment)).size!==1||rows.some((r,i)=>i&&r.time<=rows[i-1].time))throw Error('Lag Plot은 중복 없는 시간순 기록과 설비 1개를 선택하세요.');const lag=rows.slice(1).map((r,i)=>({id:rows[i].id+' → '+r.id,x:rows[i].y,y:r.y}));let rho='계산 불가';try{rho=display(CMPStats.regression(lag).r);}catch{}add(id,'Lag-1 Plot · 이전 Batch와의 연관성','직전 Y와 현재 Y의 Pearson r='+rho+'. 강한 패턴은 독립성 재검토 신호입니다. 불규칙한 측정 간격은 같은 시간 지연을 의미하지 않습니다.',chart('Lag-1 Plot','직전 Batch Y','현재 Batch Y',lag));}
 if(id==='pareto'){if(c.lsl==null&&c.usl==null)throw Error('규격 하한 또는 상한을 입력하세요.');const g=groups(rows).map(g=>({...g,fail:g.rows.filter(r=>(c.lsl!=null&&r.y<c.lsl)||(c.usl!=null&&r.y>c.usl)).length})).sort((a,b)=>b.fail-a.fail),total=g.reduce((a,b)=>a+b.fail,0);let cum=0;add(id,'규격 이탈 Pareto · 설비별','막대는 이탈 건수 순위입니다. 표의 누적 비율과 이탈률을 함께 보세요. 생산량 차이 때문에 건수 순위가 설비 위험 순위와 같지는 않습니다.',chart('설비별 이탈 건수','설비','이탈 Batch 수',g.map((g,i)=>({x:i+1,y:g.fail,lo:i+.65,hi:i+1.35,id:g.name})),{bars:true,categories:true,rangeY:[0,Math.max(1,...g.map(g=>g.fail))*1.15]})+grid(['순위','설비','전체 n','이탈 건수','이탈률 %','누적 이탈 비중 %'],g.map((g,i)=>{cum+=g.fail;return[i+1,g.name,g.rows.length,g.fail,g.fail/g.rows.length*100,total?cum/total*100:null];})));}
 }catch(e){html+='<p class="warn" data-graph-error="'+id+'">'+esc(choices.find(c=>c[0]===id)[1])+': '+esc(e.message)+'</p>';}}
 return html;
}
function wire(){document.querySelectorAll('#statResults .save-figure').forEach(button=>button.onclick=()=>{const figs=[...button.closest('.stat-figure').querySelectorAll('svg')];figs.forEach((svg,i)=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([svg.outerHTML],{type:'image/svg+xml;charset=utf-8'}));a.href=url;a.download=button.closest('.stat-figure').dataset.graph+(i?'_'+(i+1):'')+'.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});});}
root.StatsVisual={setup,render,diagnostics,wire,summary,histogram,wilson,chart};if(typeof module!=='undefined')module.exports=root.StatsVisual;
})(globalThis);
