(function(root){'use strict';
const kinds=['Batch','Material','Process','Equipment','QC','Checksheet'];
function parseCSV(s){s=s.replace(/^\uFEFF/,'');let all=[],cells=[],v='',quoted=false,closed=false,line=1,start=1;const cell=()=>{cells.push(v);v='';closed=false;};const row=()=>{cell();if(cells.some(x=>x!==''))all.push({cells,line:start});cells=[];};for(let i=0;i<s.length;i++){let ch=s[i];if(quoted){if(ch==='"'){if(s[i+1]==='"'){v+='"';i++;}else{quoted=false;closed=true;}}else{v+=ch;if(ch==='\n')line++;}continue;}if(ch==='"'){if(v||closed)throw Error(`${line}행 따옴표 오류`);quoted=true;}else if(ch===',')cell();else if(ch==='\n'||ch==='\r'){if(ch==='\r'&&s[i+1]==='\n')i++;row();line++;start=line;}else{if(closed)throw Error(`${line}행 따옴표 뒤 문자 오류`);v+=ch;}}if(quoted)throw Error('닫히지 않은 따옴표');if(v||cells.length||closed)row();if(!all.length)throw Error('빈 CSV');const headers=all.shift().cells.map(x=>x.trim());if(headers.some(x=>!x)||new Set(headers).size!==headers.length)throw Error('빈 열 이름 또는 중복 열 이름');return{headers,rows:all.map(r=>{if(r.cells.length!==headers.length)throw Error(`${r.line}행 열 수 오류`);return{...Object.fromEntries(headers.map((k,i)=>[k,r.cells[i].trim()])),_line:r.line};})};}
const time=s=>Date.parse(s),n=v=>v===''||v===null||v===undefined?null:Number(v);
function validTS(v){if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(Z|[+-]\d{2}:\d{2})$/.test(v)||!Number.isFinite(time(v)))return false;const [yr,mo,day]=v.slice(0,10).split('-').map(Number);return mo>=1&&mo<=12&&day>=1&&day<=new Date(Date.UTC(yr,mo,0)).getUTCDate()&&Number(v.slice(11,13))<24&&Number(v.slice(14,16))<60&&Number(v.slice(17,19))<60;}
function readTable(name,csv,schema,file=name+'.csv'){
 const t=parseCSV(csv),fields=schema[name],missing=fields.filter(f=>!t.headers.includes(f.name));if(missing.length)throw Error(`${file}: v2 필수 열 누락 (${missing.map(f=>f.name).join(', ')}). v1 요약 CSV는 기존 v1 프로그램에서 열 수 있습니다.`);if(t.rows.length>100000)throw Error('파일당 100,000행 이하로 나누어 주세요.');let ids=new Set();
 for(const r of t.rows){r._file=file;r._table=name;for(const f of fields)if(f.type==='number'&&/^(none|null|n\/a|na|결측치?|미측정|미기록)$/i.test(r[f.name]))r[f.name]='';if(name==='QC'&&r.Value===''&&['','EQ'].includes(r.Qualifier)){r.Qualifier='NOT_MEASURED';r._missingReason='미측정 또는 미기록: 원인 미확인';}for(const f of fields){const v=r[f.name];if(v===''){if(!f.optional)throw Error(`${file} ${r._line}행: ${f.name} 필수값 누락 (결측치, 0으로 대체하지 않음)`);continue;}if(f.type==='number'&&(!/^[+-]?(?:\d+\.?\d*|\.\d+)(e[+-]?\d+)?$/i.test(v)||!Number.isFinite(Number(v))))throw Error(`${file} ${r._line}행: ${f.name} 숫자 오류`);if(f.type==='timestamp'&&!validTS(v))throw Error(`${file} ${r._line}행: ${f.name} 유효한 ISO 시각과 시간대가 필요합니다.`);if(f.type==='boolean'&&!['true','false'].includes(v))throw Error(`${file} ${r._line}행: ${f.name} true/false 필요`);if(f.enum&&!f.enum.includes(v))throw Error(`${file} ${r._line}행: ${f.name} 지원 코드 ${f.enum.join('/')}`);}
 const id=r[fields[0].name];if(ids.has(id))throw Error(`${file} ${r._line}행: 기록 ID 중복 ${id}. 같은 Batch의 서로 다른 기록에는 서로 다른 기록 ID를 사용하세요.`);ids.add(id);
 for(const [a,b]of [['Start_TS','End_TS'],['Step_Start_TS','Step_End_TS'],['Valid_From_TS','Valid_To_TS']])if(r[a]&&r[b]&&time(r[a])>=time(r[b]))throw Error(`${file} ${r._line}행: ${a}는 ${b}보다 빨라야 합니다.`);
 if(name==='Process'&&(time(r.Event_TS)<time(r.Step_Start_TS)||time(r.Event_TS)>time(r.Step_End_TS)))throw Error(`${file} ${r._line}행: 측정 시각이 공정 구간 밖입니다.`);
 if(name==='QC'&&time(r.Sample_TS)>time(r.Result_TS))throw Error(`${file} ${r._line}행: 결과가 채취보다 빠릅니다.`);
 if(name==='QC'&&r.Value!==''&&r.Qualifier==='NOT_MEASURED')throw Error(`${file} ${r._line}행: NOT_MEASURED에 수치가 있습니다.`);
 if(name==='QC'&&r.Value===''&&r.Qualifier!=='NOT_MEASURED')throw Error(`${file} ${r._line}행: 수치가 없으면 NOT_MEASURED를 지정하세요.`);
 if(name==='QC'&&n(r.LSL)!==null&&n(r.USL)!==null&&n(r.LSL)>n(r.USL))throw Error(`${file} ${r._line}행: LSL > USL`);
 }
 const byBatch={};for(const r of t.rows)if(r.Batch_ID)(byBatch[r.Batch_ID]??=[]).push(r);
 return{...t,name,filename:file,byBatch};
}
function classify(schema,headers){const a=kinds.filter(k=>{const fields=schema[k];return fields.some(f=>headers.includes(f.name))&&fields.filter(f=>!f.optional).every(f=>headers.includes(f.name));});if(a.length!==1)throw Error('파일 종류를 식별할 수 없습니다. v2 양식의 열 이름을 확인하세요.');return a[0];}
function overlaps(a,b,c,d){return Math.max(time(a),time(c))<Math.min(time(b),time(d));}
function scopeMatch(r,b){return r.Scope_Type==='BATCH'?r.Scope_ID===b.Batch_ID:r.Scope_Type==='EQUIPMENT'?r.Scope_ID===b.Equipment_ID:r.Scope_Type==='LINE'?r.Scope_ID===b.Line_ID:r.Scope_Type==='SITE'?r.Scope_ID===b.Site_ID:false;}
function coverage(start,end,rows){let cursor=time(start),finish=time(end),gaps=[];const ranges=rows.map(r=>[Math.max(time(start),time(r.Valid_From_TS)),Math.min(finish,time(r.Valid_To_TS))]).filter(([a,z])=>a<z).sort((a,b)=>a[0]-b[0]);for(const[a,z]of ranges){if(a>cursor)gaps.push([cursor,a]);cursor=Math.max(cursor,z);}if(cursor<finish)gaps.push([cursor,finish]);return gaps;}
function source(r){return r?`${r._file} · ${r._line}행 · ${Object.values(r)[0]}`:'연결 기록 없음';}
function rangeMessage(name,b,provenance){const p=provenance[name];if(!p?.from||!p?.to)return '파일 추출 범위가 미지정입니다. 조회 조건·기록 완료 여부를 확인하세요.';return `선언한 추출 범위 ${p.from} ~ ${p.to} (${p.basis}). 이전 교대 또는 이후 결과 확정 기록이 제외되었는지 확인하세요.`;}
function judgeQC(r,origin){if(r.Qualifier==='NOT_MEASURED'||r.Value==='')return '미측정';if(r.Qualifier!=='EQ')return '검토 필요';let l=n(r.LSL),u=n(r.USL);if(r.Spec_Status==='UNSPECIFIED'&&origin==='SYNTHETIC'&&(r.Spec_Rev==='UNSPECIFIED'||r.Spec_Rev===''||r.Spec_Rev==='SIM-Q01')){const d={pH:[9.5,10.5],Solids:[9.5,10.5],Viscosity:[1.2,2.2],D50:[75,105],D90:[110,180],LPC_0p5:[null,3000],LPC_1p0:[null,600],Zeta:[-50,-30],Fe:[null,1]}[r.Analyte_ID];if(d){l=d[0];u=d[1];}}if(l===null&&u===null)return '규격 없음';if(r.Spec_Status==='DEMO'&&(origin!=='SYNTHETIC'||r.Data_Origin!=='SYNTHETIC'))return '시연 규격 미적용';const v=n(r.Value);return(l!==null&&v<l)||(u!==null&&v>u)?'규격 이탈':'규격 내';}
function checklist(t,b,scope='LINE',type='SHIFT_PRESTART'){
 const linked=t.rows.filter(r=>scopeMatch(r,b)&&overlaps(b.Start_TS,b.End_TS,r.Valid_From_TS,r.Valid_To_TS));const required=linked.filter(r=>r.Scope_Type===scope&&r.Checklist_Type===type);
 const timely=required.filter(r=>time(r.Completed_TS)<=Math.max(time(b.Start_TS),time(r.Valid_From_TS)));let conflicts=[];
 for(let i=0;i<required.length;i++)for(let j=i+1;j<required.length;j++)if(overlaps(required[i].Valid_From_TS,required[i].Valid_To_TS,required[j].Valid_From_TS,required[j].Valid_To_TS)&&overlaps(b.Start_TS,b.End_TS,new Date(Math.max(time(required[i].Valid_From_TS),time(required[j].Valid_From_TS))).toISOString(),new Date(Math.min(time(required[i].Valid_To_TS),time(required[j].Valid_To_TS))).toISOString()))conflicts.push([required[i],required[j]]);
 return{linked,required,timely,gaps:coverage(b.Start_TS,b.End_TS,timely),conflicts,late:required.filter(r=>!timely.includes(r))};
}
function investigate(t,bid,opt={}){
 const b=t.Batch.byBatch[bid]?.[0];if(!b)throw Error('Batch ID를 찾을 수 없습니다. 날짜 필터와 입력값을 확인하세요.');const scope=opt.scope||'LINE',type=opt.type||'SHIFT_PRESTART',provenance=opt.provenance||{};
 const m=t.Material.byBatch[bid]||[],p=t.Process.byBatch[bid]||[],q=t.QC.byBatch[bid]||[];const e=t.Equipment.rows.filter(r=>r.Equipment_ID===b.Equipment_ID&&overlaps(b.Start_TS,b.End_TS,r.Valid_From_TS,r.Valid_To_TS));const ck=checklist(t.Checksheet,b,scope,type);let findings=[];
 const add=(kind,title,detail,rows=[])=>findings.push({kind,title,detail,sources:rows.map(source)});
 for(const[name,rows]of [['Material',m],['Process',p],['QC',q],['Equipment',e]])if(!rows.length)add('missing',`${name} 연결 기록 없음`,rangeMessage(name,b,provenance));
 if(!ck.required.length)add('missing','적용 가능한 교대 점검 기록 없음',`${scope} / ${type} 기준. ${rangeMessage('Checksheet',b,provenance)} 실제 미점검으로 단정하지 않습니다.`);
 if(ck.gaps.length)add('missing','점검 적용시간 미확인 구간',ck.gaps.map(([a,z])=>new Date(a).toISOString()+' ~ '+new Date(z).toISOString()).join(', '));
 if(ck.late.length)add('review','적용 시작 이후 작성된 점검', '작성 이전 구간에 점검 완료를 소급 가정하지 않았습니다.',ck.late);
 if(ck.conflicts.length)add('integrity','같은 범위의 점검 유효구간 중복','어느 기록이 승인된 적용 기록인지 확인하세요. 마지막 행을 임의로 선택하지 않습니다.',[...new Set(ck.conflicts.flat())]);
 const failed=ck.required.filter(r=>r.Result!=='PASS');if(failed.length)add('review','교대 점검 결과 확인 필요',failed.map(r=>r.Result+' / '+r.Comment).join('; '),failed);
 for(const r of p){if(r.Equipment_ID!==b.Equipment_ID)add('integrity','공정 설비 불일치',`Batch 설비 ${b.Equipment_ID}, 측정 설비 ${r.Equipment_ID}`,[r]);if(time(r.Step_Start_TS)<time(b.Start_TS)||time(r.Step_End_TS)>time(b.End_TS))add('integrity','공정 구간이 Batch 기간 밖','기간 또는 Batch ID를 확인하세요.',[r]);}
 for(const r of m)if(time(r.Charge_TS)<time(b.Start_TS)||time(r.Charge_TS)>time(b.End_TS))add('integrity','원료 투입 시각이 Batch 기간 밖',r.Charge_TS,[r]);
 const steps=Object.values(p.reduce((a,r)=>{const key=[r.Step_Run_ID,r.Step_ID].join('|');if(!a[key])a[key]={id:r.Step_Run_ID,step:r.Step_ID,start:r.Step_Start_TS,end:r.Step_End_TS,rows:[]};else if(time(a[key].start)!==time(r.Step_Start_TS)||time(a[key].end)!==time(r.Step_End_TS))add('integrity','동일 공정 실행의 시간 불일치',key,[r]);a[key].rows.push(r);return a;},{})).sort((a,b)=>time(a.start)-time(b.start));
 const proc=Object.values(p.reduce((a,r)=>{const key=[r.Step_Run_ID,r.Parameter,r.Unit].join('|');if(!a[key])a[key]={step:r.Step_ID,parameter:r.Parameter,unit:r.Unit,rows:[],values:[]};a[key].rows.push(r);a[key].values.push(n(r.Value));return a;},{})).map(g=>({...g,count:g.values.length,min:Math.min(...g.values),max:Math.max(...g.values),mean:g.values.reduce((a,b)=>a+b,0)/g.values.length}));
 for(const group of proc){if(b.Data_Origin==='SYNTHETIC'&&b.Recipe_Rev==='SIM-R02'&&group.rows.every(r=>r.Data_Origin==='SYNTHETIC')){const threshold=group.parameter==='Temperature'&&group.unit==='C'?30:group.parameter==='Filter_DP'&&group.unit==='kPa'?80:null;if(threshold!==null&&group.max>threshold)add('review',`${group.parameter} 등록 검토 기준 초과`,`최대 ${group.max} ${group.unit}; 시연 기준 > ${threshold}. 원시 측정 간격이 달라 연속 초과시간은 계산하지 않습니다.`,group.rows.filter(r=>n(r.Value)>threshold));}}
 const analytes=Object.values(q.reduce((a,r)=>{(a[r.Analyte_ID]??=[]).push(r);return a;},{})).map(rows=>{rows.sort((a,b)=>time(a.Result_TS)-time(b.Result_TS));const finals=rows.filter(r=>r.Is_Final==='true'&&r.Approval_Status==='APPROVED'&&r.Qualifier!=='NOT_MEASURED');const result=finals.length===1?finals[0]:null;
 if(!finals.length)add('missing',`${rows[0].Analyte_ID} 최종 승인 결과 없음`,'최초·재시험을 보존했습니다. 이후 결과가 추출 범위에서 제외되었는지 확인하세요.',rows);
 if(finals.length>1)add('integrity',`${rows[0].Analyte_ID} 최종 승인 결과 중복`,'최종값을 임의로 선택하지 않습니다. Is_Final과 승인 상태를 확인하세요.',finals);
 const allOOS=rows.filter(r=>judgeQC(r,b.Data_Origin)==='규격 이탈');if(allOOS.length)add('oos',`${rows[0].Analyte_ID} 시험 이력의 규격 이탈`,result&&judgeQC(result,b.Data_Origin)==='규격 내'?'재시험 최종값은 규격 내지만 최초 이탈 이력을 유지합니다.':'입력 규격의 판정입니다. 품질 담당자 검토가 필요합니다.',allOOS);
 const methods=new Set(rows.map(r=>[r.Unit,r.Method_ID,r.Spec_Rev].join('|')));if(methods.size>1)add('review',`${rows[0].Analyte_ID} 시험 조건 변경`,'방법·단위·규격 개정이 서로 다릅니다. 평균이나 단순 증감을 계산하지 않습니다.',rows);
 return {id:rows[0].Analyte_ID,rows,final:result,state:result?judgeQC(result,b.Data_Origin):finals.length?'최종값 중복':'최종값 없음'};});
 // Final specifications are not inferred from whichever tests happened to be imported.
 let panel='필수항목 목록 미등록';const expected=['pH','Solids','Viscosity','D50','D90','LPC_0p5','LPC_1p0','Zeta','Fe'];if(b.Product_ID==='SIM-OX-02'&&b.Recipe_Rev==='SIM-R02'&&b.Data_Origin==='SYNTHETIC'){const missing=expected.filter(id=>!analytes.some(x=>x.id===id));if(missing.length)add('missing','등록 QC 항목의 항목 누락',missing.join(', '));panel=missing.length||analytes.some(x=>!x.final||!['규격 내','규격 이탈'].includes(x.state))?'판정 불완전':analytes.some(x=>x.state==='규격 이탈')?'최종 결과 이탈':'최종 결과 규격 내';}
 const material=Object.values(m.reduce((a,r)=>{const key=[r.Material_ID,r.Lot_ID,r.Unit].join('|');if(!a[key])a[key]={material:r.Material_ID,lot:r.Lot_ID,unit:r.Unit,quantity:0,rows:[]};a[key].quantity+=n(r.Quantity);a[key].rows.push(r);return a;},{}));
 const declared=provenance.Checksheet;if(declared?.from&&declared?.to){if(time(declared.from)>time(b.Start_TS)||time(declared.to)<time(b.End_TS))add('missing','체크시트 추출 범위가 Batch를 덮지 않음',`선언 범위 ${declared.from} ~ ${declared.to}. 실제 미점검으로 단정하지 않고 재조회 대상으로 표시합니다.`);}
 const shared=ck.linked.map(r=>({row:r,batchCount:t.Batch.rows.filter(x=>scopeMatch(r,x)&&overlaps(x.Start_TS,x.End_TS,r.Valid_From_TS,r.Valid_To_TS)).length}));
 const order={integrity:0,missing:1,oos:2,review:3};findings.sort((a,b)=>order[a.kind]-order[b.kind]);return{bid,b,material,process:proc,steps,qc:analytes,equipment:e,check:ck,shared,findings,panel,records:{Batch:[b],Material:m,Process:p,Equipment:e,QC:q,Checksheet:ck.linked},provenance,scope,type,generated:new Date().toISOString(),version:'2.0'};
}
function filterBatches(rows,from,to){const a=from?time(from+'T00:00:00+09:00'):-Infinity,z=to?time(to+'T00:00:00+09:00')+86400000:Infinity;if(a>=z)throw Error('시작일은 종료일보다 늦을 수 없습니다.');return rows.filter(r=>time(r.Start_TS)>=a&&time(r.Start_TS)<z);}
root.CMP2={kinds,parseCSV,readTable,classify,scopeMatch,coverage,checklist,investigate,filterBatches,judgeQC,source,time};if(typeof module!=='undefined')module.exports=root.CMP2;
})(globalThis);
